# Generated by Django 5.0.1 on 2025-03-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myprofile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsarticle",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
