# Generated by Django 5.0.1 on 2025-03-19 10:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myprofile", "0002_alter_newsarticle_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newsarticle",
            old_name="created_at",
            new_name="date",
        ),
    ]
